services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  airflow:
    build: . 
    depends_on:
      - postgres
    
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "this-is-a-stable-airflow-secret-key-change-me"
      AIRFLOW__API__SECRET_KEY: "this-is-a-stable-airflow-secret-key-change-me"
      SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY}
      PYTHONPATH: /opt/airflow/dags
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datalake_bronze:/opt/airflow/datalake/bronze
      - ./datalake_silver:/opt/airflow/datalake/silver
      - ./datalake_gold:/opt/airflow/datalake/gold
    entrypoint: >
      bash -c "airflow db upgrade &&
      airflow users create
      --username admin --firstname Air --lastname Flow
      --role Admin --email admin@example.com
      --password admin || true &&
      airflow webserver & airflow scheduler"
volumes:
  pgdata: